pipeline {
    agent any
    
    environment {
        PROJECT_DIR = "/var/jenkins_home/healthy-project/HealthyIAC"
        BACKEND_DIR = "/var/jenkins_home/healthy-project/BackEnd"
        FRONTEND_DIR = "/var/jenkins_home/healthy-project/FrontEnd"
        AWS_REGION = "us-east-1"
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/jlescanoguti/Despliegue-de-aplicacion-Healthy-IaC.git',
                credentialsId: 'github-creds'  // Usando tus credenciales GitHub
            }
        }
        
        stage('Build Backend') {
            steps {
                dir(BACKEND_DIR) {
                    sh 'mvn clean package'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
        
        stage('Terraform Plan') {
            steps {
                dir(PROJECT_DIR) {
                    withAWS(credentials: 'aws-healthy-creds', region: AWS_REGION) {  // Credenciales AWS actualizadas
                        sh 'terraform init'
                        sh 'terraform plan'
                    }
                }
            }
        }
        
        stage('Deploy Infrastructure') {
            when {
                branch 'main'
            }
            steps {
                dir(PROJECT_DIR) {
                    withAWS(credentials: 'aws-healthy-creds', region: AWS_REGION) {  // Credenciales AWS actualizadas
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
        
        stage('Deploy Backend') {
            steps {
                script {
                    // Usando las credenciales AWS configuradas
                    withAWS(credentials: 'aws-healthy-creds', region: AWS_REGION) {
                        def backend_ips = sh(
                            script: 'aws ec2 describe-instances --filters "Name=tag:Name,Values=Healthy-Backend" --query "Reservations[].Instances[].PrivateIpAddress" --output text',
                            returnStdout: true
                        ).trim()
                        
                        backend_ips.split(' ').each { ip ->
                            sh "scp -o StrictHostKeyChecking=no ${BACKEND_DIR}/target/*.jar ec2-user@${ip}:/home/ec2-user/app.jar"
                            sh "ssh -o StrictHostKeyChecking=no ec2-user@${ip} 'sudo systemctl restart backend.service'"
                        }
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
        failure {
            mail to: 'caguilari1@upao.edu.pe',  // Reemplaza con tu email real
            subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
            body: "El pipeline ha fallado. Ver detalles: ${env.BUILD_URL}"
        }
    }
}